apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: say-hello
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: say-hello
    spec:
      containers:
      - name: say-hello
        image: us.gcr.io/kube-test-204901/src1:build-1

