apiVersion: v1
kind: Pod
  metadata:
    labels:
      app: my-app
  spec:
    containers:
    - name: my-app
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
      env:
      - name: ENV_VAR_1
        value: VALUE_1