global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
# JOBS AND INSTANCES
# In Prometheus terms, an endpoint you can scrape is called an instance, usually corresponding to a single process. 
# A collection of instances with the same purpose, a process replicated for scalability or reliability for example, is called a job.
#
# For example, an API server job with four replicated instances:
#
#job: api-server
#  instance 1: 1.2.3.4:5670
#  instance 2: 1.2.3.4:5671
#  instance 3: 5.6.7.8:5670
#  instance 4: 5.6.7.8:5671
- job_name: dummy-app # 
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - dummy-app-a:5000 # address of our dummy app instance a
    - dummy-app-b:5001 # address of our dummy app instance b


