version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  prom-demo:

services:
  dummy-app-a:
    build:
      context: ../.
    environment:
      - ADDR=:5000
      - WORKER_NAME=worker_a
    ports:
      - 5000:5000

  dummy-app-b:
    build:
      context: ../.
    environment:
      - ADDR=:5001
      - WORKER_NAME=worker_b
    ports:
      - 5001:5001

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - grafana.config.env